[metadata]
id = "railway-django"
title = "Demo for Django"
version = "0.1"
release = 1
license = "MIT"
src-url = "https://github.com/railwayapp-templates/django/archive/refs/heads/main.tar.gz"

[build]
build-packages = [
    # Needed to build psycopg2
    "gcc",
    "python3-dev",
    "libpq-dev",
]
