[metadata]
id = "peertube"
title = "PeerTube"
author = "PeerTube authors"
description = "ActivityPub-federated video streaming platform using P2P directly in your web browser"
website = "https://joinpeertube.org/"
version = "5.1.0"
release = 1
license = "AGPL-3.0"

src-url = "https://github.com/Chocobozzz/PeerTube/archive/v{version}.tar.gz"

[build]
# Note: incompatible w/ Node 20.
builder = "node"

# TODO: should be autodetected
build-command = [
    "yarn",
    "yarn run build",
]
test = [
    "test -f ./dist/server/tests/cli/peertube.js",
]
