[metadata]
id = "peertube"
title = "PeerTube"
author = "PeerTube authors"
description = "ActivityPub-federated video streaming platform using P2P directly in your web browser"
website = "https://joinpeertube.org/"
version = "5.0.1"
release = 1
license = "AGPL-3.0"

src-url = "https://github.com/Chocobozzz/PeerTube/archive/v{version}.tar.gz"

[build]
# Note: incompatible w/ Node 20.
builder = "node"
build-command = [
    "yarn",
    "yarn run build",
]
test = [
    "find . -name peertube.js",
    "test -f dist/server/tools/peertube.js",
]
