#
# Skipped for now because it takes 10 times longer to build than the other apps.
#

[metadata]
id = "railway-rocket"
title = "Demo for Rust + Rocket"
author = "Railway"
version = "0.1"
release = 1
license = "MIT"
src-url = "https://github.com/railwayapp-templates/rocket/archive/refs/heads/main.tar.gz"

[builder]
builder = "rust"

[run]
start-command = "cargo run --release"
