[metadata]
id = "railway-deno"
title = "Demo demo app from Railway"
author = "deno authors"
description = "A simple web server built with Deno."
website = "https://github.com/railwayapp-templates/deno/"
version = "???"
release = 1
license = "MIT"

src-url = "https://github.com/railwayapp-templates/deno/archive/refs/heads/main.tar.gz"

[build]
builder = "deno"

build-packages = []

[run]
# Doesn't work with Deno 1.32.4
start-command = "deno --allow-net --allow-env src/index.ts"
