[metadata]
id = "railway-django"
title = "Demo for Django"
author = "Railway"
website = "https://github.com/railwayapp-templates/django/"
version = "0.1"
release = 1
license = "MIT"
src-url = "https://github.com/railwayapp-templates/django/archive/refs/heads/main.tar.gz"

[build]
builder = "python"
build-packages = [
    # Needed to build psycopg2
    "gcc",
    "python3-dev",
    "libpq-dev",
]

[run]
start-command = "gunicorn app:app"
