[metadata]
id = "render-vuepress"
title = "Demo Vuepress"
author = "Render"
version = "0.1"
release = 1
license = "MIT"
src-url = "https://github.com/render-examples/vuepress/archive/refs/heads/master.zip"

[build]
builder = "node-16"
build-command = [
    "npm install",
    "npm run build",
]
test = "find . -name index.js"
#test = "test -f build/index.js"

[run]
# This is a static app. No need to start anything.
