image: ubuntu/lts

packages:
  # Build tools
  - software-properties-common
  - build-essential
  - make
  - gcc
  - g++
  # Python
  - python3-dev
  - python3-pip
  - python3-wheel
  - tox
  # Libraries
  - libpq-dev
  - libffi-dev
  - libsqlite3-dev
  - libbz2-dev
  # Tools
  - vagrant
  - virtualbox
  - docker.io

tasks:
  - setup: |
      sudo pip install -U pip setuptools wheel poetry nox invoke
      cd nua-sandbox

  - nox-lint: |
      cd nua-sandbox
      nox -e lint

  - lint: |
      cd nua-sandbox
      poetry run invoke install
      poetry run invoke lint

#  - e2e: |
#      cd nua/tests/e2e
#      poetry run make test

  - test: |
      cd nua-sandbox
      poetry run invoke test

  - nox-test: |
      cd nua-sandbox
      nox -e pytest


triggers:
  - action: email
    condition: failure
    to: builds@fermigier.com
