[metadata]
id = "matomo"
title = "matomo"
author = "matomo authors"
description = "Liberating Web Analytics. Star us on Github? +1. Matomo is the leading open alternative to Google Analytics that gives you full control over your data. Matomo lets you easily collect data from websites & apps and visualise this data and extract insights. Privacy is built-in. We love Pull Requests! "
website = "https://matomo.org/"
repo = "https://github.com/matomo-org/matomo"
version = "4.14.2"
release = 1
license = "GPL-3.0"

src-url = "https://github.com/matomo-org/matomo/archive/{version}.tar.gz"

[build]
builder = "php"
packages = [
    "libfreetype6-dev",
    "libjpeg-dev",
    "libldap2-dev",
    "libpng-dev",
    "libzip-dev",
    "procps",
    "php-curl",
    "php-gd",
]
# builders = ["php", "node"]
