[metadata]
id = "render-demo-rails"
title = "Demo for Rails 6"
version = "0.1"
release = 1
license = "MIT"
src-url = "https://github.com/render-examples/rails-6/archive/refs/heads/master.tar.gz"

[build]
builder = "ruby"

[run]
start-command = "bundle exec puma -C config/puma.rb"
