[metadata]
id = "moodle"
title = "Moodle"
author = "Moodle authors"
description = "Moodle - the world's open source learning platform"
website = "https://moodle.org/"
repo = "https://github.com/moodle/moodle/"
version = "4.2.0"
release = 1
license = "GPL-3.0"

src-url = "https://github.com/moodle/moodle/archive/v{version}.tar.gz"

[build]
packages = [
    "php-zip",
    "php-gd",
]

# Note: it's currently incorrectly detected as a Node.js app.
builder = "php"
# Should be:
# builders = ["php", "node"]
# (Or detected automatically.)
