[metadata]
id = "adhocracy-plus"
title = "adhocracy-plus"
author = "adhocracy-plus authors"
description = "adhocracy+ is a SaaS platform to make digital democracy easy for everyone"
website = "https://adhocracy.plus/"
version = "2306.3"
release = 1
license = "AGPL-3.0"

repo-url = "https://github.com/liqd/adhocracy-plus/"
src-url = "https://github.com/liqd/adhocracy-plus/archive/v{version}.tar.gz"

[build]
builder = "python"
packages = [
    "git",
    # Needed to build psycopg2
    "libpq-dev",
    # Needed for some reason
    "libcairo2-dev",
]
