[metadata]
id = "etherpad-lite"
title = "etherpad-lite"
author = "etherpad-lite authors"
description = "Etherpad: A modern really-real-time collaborative document editor."
website = "https://etherpad.org"
version = "1.8.18"
release = 1
license = "Apache-2.0"

src-url = "https://github.com/ether/etherpad-lite/archive/{version}.tar.gz"

[build]
build-packages = []
