[metadata]
id = "render-rails"
title = "Demo for Rails 6"
author = "Render"
website = "https://github.com/render-examples/rails-6/"
version = "0.1"
release = 1
license = "MIT"
src-url = "https://github.com/render-examples/rails-6/archive/refs/heads/master.zip"

[build]
builder = "ruby"
packages = [
    "libpq-dev",
]
before-build = "python3 nua/fix-sources.py"

[run]
start-command = "bundle exec puma -C config/puma.rb"
