[metadata]
id = "cal.com"
version = "1.9.6"
release = 11
title = "Cal.com"
author = "Cal.com developers"
tagline = ""
website = "https://cal.com/"
tags = ["Scheduling"]
license = "AGPL-3.0"
src-url = "https://github.com/calcom/cal.com/archive/refs/heads/main.tar.gz"

[build]
builder = "node-16"

build-script = "build.sh"
