[metadata]
id = "render-sveltekit"
title = "sveltekit"
author = "Render"
description = "Deploy SvelteKit to Render using the Node.js adapter"
website = "https://github.com/render-examples/sveltekit/"
version = "???"
release = 1
license = "???"

src-url = "https://github.com/render-examples/sveltekit/archive/refs/heads/main.tar.gz"

[build]
builder = "nodejs"
build-command = "npm install && npm run build"

[run]
run-command = "node build/index.js"
