[metadata]
id = "wekan"
title = "Wekan"
author = "Wekan developers"
tagline = "Open-source kanban boards"
license = "MIT"

version = "6.86"
website = "https://wekan.github.io/"
tags = ["kanban", "planning", "project"]

src-url = "https://github.com/wekan/wekan/archive/refs/tags/v{version}.tar.gz"

[build]
builder = "node"

# Notes:
# Technology used: Meteor

#[addons]
#local-storage = { }
#mongodb = { }
#sendmail = { }
#ldap = { }

#[run]
#health-check-path = "/"
#http-port = 3_000
