[metadata]
id = "railway-flask"
title = "Demo for Flask"
author = "Railway"
website = "https://github.com/railwayapp-templates/flask/"
version = "0.1"
release = 1
license = "MIT"
src-url = "https://github.com/railwayapp-templates/flask/archive/refs/heads/main.tar.gz"

#
# Warning: doesn't work currently because we need to put app in a virtualenv
# (to prevent conflcit between nua-agent's jinja2 and the app's jinja2)
#

[build]
builder = "python"
test = "python -c 'import app'"


[run]
start-command = "gunicorn app:app"
