[metadata]
id = "limesurvey"
title = "LimeSurvey"
author = "LimeSurvey authors"
description = "The most popular FOSS online survey tool on the web."
website = "https://www.limesurvey.org"
version = "6.0.4+230427"
release = 1
license = "GPLv2+"

src-url = "https://github.com/LimeSurvey/LimeSurvey/archive/{version}.tar.gz"

[build]
builder = "php"
