[metadata]
id = "clever-go"
title = "Go-example from Clever Cloud"
author = "Go-example authors"
description = "A Go app example"
website = "https://github.com/CleverCloud/Go-example/"
version = "???"
release = 1
license = "???"

src-url = "https://github.com/CleverCloud/Go-example/archive/refs/heads/main.tar.gz"

[build]
builder = "go"

[run]
start-command = "go run main.go"
