[metadata]
id = "render-express"
title = "Demo ExpressJS"
author = "Render"
website = "https://github.com/render-examples/express-hello-world/"
version = "0.1"
release = 1
license = "MIT"
src-url = "https://github.com/render-examples/express-hello-world/archive/refs/heads/main.tar.gz"

[build]
builder = "node-16"

[run]
start-command = "node app.js"
