[metadata]
id = "railway-rails"
title = "Demo for Ruby on Rails"
author = "Railway"
website = "https://github.com/railwayapp-templates/ruby-rails/"
version = "0.1"
release = 1
license = "MIT"
src-url = "https://github.com/railwayapp-templates/ruby-rails/archive/refs/heads/main.tar.gz"

[build]
builder = "ruby"
packages = [
    "libpq-dev",
]
before-build = "python3 nua/fix-sources.py"

[run]
